@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}
@api = {{host}}/api
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@system = skylane-hrm-_{{$guid} }

#####################################################


###
GET {{api}}/seed

###
###
# @name loginReq
POST {{api}}/users/login
Content-Type: application/json

{"inputData":"test2@gmail.com","password":"test2@gmail.com"}
###
POST {{api}}/users/register
Content-Type: application/json

{
  "name":"test2@gmail.com",
  "email":"test2@gmail.com",
  "phoneNumber":"test2@gmail.com",
  "password":"test2@gmail.com"
}

###
GET {{api}}/users
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/self
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "email":"test2@gmail.com",
  "email3":"test23@gmail.com"
}



###
POST {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{ "name":"test2@gmail.com" }

###
GET {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com"
}

###
GET {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
###
POST {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive"
}
###
GET {{api}}/departments
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/designations
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/duty-types
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/salary-types
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "eId": "{{$guid}}",
  "name": "test266@gmail.com",
  "phoneNumber": "test266@gmail.com",
  "altPhoneNumber": "test266@gmail.com",
  "dateOfBirth": "1999-01-01",
  "email": "test266@gmail.com",
  "fullAddress": "test266@gmail.com",
  "gender": "Male",
  "photo": "",
  "company": {
    "id": 1,
    "name": "Soap pixel Frozen",
    "logo": "http://placeimg.com/50/50/business",
    "status": "inactive"
  },
  "department": {
    "id": 1,
    "name": "tan Florida",
    "status": "inactive"
  },
  "branch": {
    "id": 1,
    "name": "payment neural",
    "status": "active"
  },
  "designation": {
    "id": 1,
    "name": "invoice",
    "status": "active"
  },
  "dutyType": {
    "id": 1,
    "name": "Mobilitysdsd",
    "status": "active"
  },
  "salaryType": {
    "id": 1,
    "name": "compressingdsdsdasd",
    "status": "inactive"
  },
  "dateOfJoining": "1999-01-01",
  "unitSalary": 0,
  "taskWisePayment": 0,
  "wordLimit": 0,
  "officeEndTime": "11:00:00",
  "officeStartTime": "06:00:00",
  "checkedInLateFee": "inApplicable",
  "overtime": "inApplicable",
  "noticePeriod": "2029-01-01",
  "extraBonus": "inApplicable",
  "status": "active",
  "createdDate": "1999-01-01"
}

###
GET {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/employees/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/employees/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com"
}