@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}
@api = {{host}}/api
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@system = skylane-hrm-_{{$guid} }

#####################################################


###
GET {{api}}/seed

###
###
# @name loginReq
POST {{api}}/users/login
Content-Type: application/json

{"inputData":"test2@gmail.com","password":"test2@gmail.com"}
###
POST {{api}}/users/register
Content-Type: application/json

{
  "name":"test2@gmail.com",
  "email":"test2@gmail.com",
  "phoneNumber":"test2@gmail.com",
  "password":"test2@gmail.com"
}

###
POST {{api}}/users/register
Content-Type: application/json

{
  "name":"test3@gmail.com",
  "email":"test3@gmail.com",
  "phoneNumber":"test3@gmail.com",
  "password":"test3@gmail.com",
  "type": "SuperAdmin"
}
###
GET {{api}}/users
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
# @name userReq
GET {{api}}/users/25
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/self
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "email":"test2@gmail.com",
  "email3":"test23@gmail.com"
}



###
POST {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{ "name":"test2@gmail.com" }

###
GET {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com"
}

###
GET {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
###
POST {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive"
}
###
GET {{api}}/departments
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/designations
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/duty-types
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/salary-types
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name": "test266@gmail.com",
  "phoneNumber": "test266@gmail.com",
  "altPhoneNumber": "test266@gmail.com",
  "dateOfBirth": "1999-01-01",
  "email": "test266@gmail.com",
  "fullAddress": "test266@gmail.com",
  "gender": "Male",
  "photo": "",
  "company": {"id": 1},
  "department": {"id": 1},
  "branch": {"id": 1},
  "designation": {"id": 1},
  "dutyType": {"id": 1},
  "salaryType": {"id": 1},
  "dateOfJoining": "1999-01-01",
  "basicSalary": 0,
  "houseRent": 0,
  "foodCost": 0,
  "conveyance": 0,
  "medicalCost": 0,
  "totalSalary": 0,
  "taskWisePayment": 0,
  "wordLimit": 0,
  "officeStartTime": "06:00",
  "officeEndTime": "11:00:12",
  "checkedInLateFee": "inApplicable",
  "overtime": "inApplicable",
  "extraBonus": "inApplicable",
  "status": "active",
  "createdDate": "1999-01-01",
  "assets": [
    {
      "name": "ss",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    }
  ],
  "contacts": [],
  "financials": []
}

###
GET {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/employees/assets
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/employees/76
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/employees/75
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com",
  "branch": { "id":3, "name": "c" },
  "assets": [
    {
      "name": "ssadasda",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    },{
      "name": "ssfsadsdsad",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    },{
      "name": "ssfsadsssdsad",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    }
  ]
}


###
GET {{api}}/attendances?from=2024-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/attendances/companywise?date=2024-02-16
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/attendances/75?from=2024-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/attendances
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

[
  { "arrivalTime": "09:12:12", "leaveTime": "11:12:12", "date": "2024-02-15", "employee": {"id": 75} },
  { "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-16", "employee": {"id": 75} },
  { "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-17", "employee": {"id": 75, "names": "ho"} }
]
###
PUT {{api}}/attendances/12
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-16", "employee": {"id": 75} }

###
DELETE {{api}}/attendances/12
Authorization: Bearer {{loginReq.response.body.$.token}}



###
GET {{api}}/leaves?from=2011-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/leaves/75?from=2024-02-16&to=2024-02-17
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/leaves?from=2023-12-15&to=2024-12-14
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{
  "from": "2024-02-16",
  "to": "2024-02-17",
  "reason": "Chill",
  "type": "paid",
  "status": "pending",
  "duration": "fullday",
  "shift": "firstHalfDay",
  "employee": {"id": 75}
}
###
PUT {{api}}/leaves/12
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "shift": "secondHalfDay" }

###
DELETE {{api}}/leaves/1
Authorization: Bearer {{loginReq.response.body.$.token}}



###
GET {{api}}/salaries?from=2011-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/salaries/75?from=2024-02-16&to=2024-02-17
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/salaries?from=2023-12-15&to=2024-12-14
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{
  "month": "2024-01-01",
  "paidAt": "2024-01-14",
  "overtime": 6,
  "overtimePayment": 345,
  "lateMinutes": 5,
  "latePenalty": 14,
  "bonus": 4,
  "totalSalary": 3456,
  "paymentMethod": "bKash",
  "status": "paid",
  "employee": {"id": 75}
}
###
PUT {{api}}/salaries/1
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "status": "paid" }

###
DELETE {{api}}/salaries/1
Authorization: Bearer {{loginReq.response.body.$.token}}