@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}
@api = {{host}}/api
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@system = hrm-_{{$guid} }

#####################################################


###
GET {{api}}/seed
###
GET {{api}}/seedEmployees

###
###
# @name loginReq
POST {{api}}/users/login
Content-Type: application/json

{"inputData":"test2@gmail.com","password":"test2@gmail.com"}
###
POST {{api}}/users/register
Content-Type: application/json

{
  "name":"test2@gmail.com",
  "email":"test2@gmail.com",
  "phoneNumber":"test2@gmail.com",
  "password":"test2@gmail.com"
}

###
POST {{api}}/users/register
Content-Type: application/json

{
  "name":"test3@gmail.com",
  "email":"test3@gmail.com",
  "phoneNumber":"test3@gmail.com",
  "password":"test3@gmail.com",
  "type": "SuperAdmin"
}
###
GET {{api}}/users
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
# @name userReq
GET {{api}}/users/25
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/users/self
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/users/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "email":"test2@gmail.com",
  "email3":"test23@gmail.com"
}



###
POST {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{ "name":"test2@gmail.com" }

###
GET {{api}}/companies
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/companies/1
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com"
}

###
GET {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
###
POST {{api}}/branches
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive"
}
###
GET {{api}}/departments
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/designations
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/duty-types
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/salary-types
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name": "test266@gmail.com",
  "phoneNumber": "test266@gmail.com",
  "altPhoneNumber": "test266@gmail.com",
  "dateOfBirth": "1999-01-01",
  "email": "test266@gmail.com",
  "fullAddress": "test266@gmail.com",
  "gender": "Male",
  "photo": "",
  "company": {"id": 1},
  "department": {"id": 1},
  "branch": {"id": 1},
  "designation": {"id": 1},
  "dutyType": {"id": 1},
  "salaryType": {"id": 1},
  "dateOfJoining": "1999-01-01",
  "basicSalary": 0,
  "houseRent": 0,
  "foodCost": 0,
  "conveyance": 0,
  "medicalCost": 0,
  "totalSalary": 0,
  "taskWisePayment": 0,
  "wordLimit": 0,
  "officeStartTime": "06:00",
  "officeEndTime": "11:00:12",
  "checkedInLateFee": "inApplicable",
  "overtime": "inApplicable",
  "extraBonus": "inApplicable",
  "status": "active",
  "createdDate": "1999-01-01",
  "assets": [
    {
      "name": "ss",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    }
  ],
  "contacts": [],
  "financials": []
}

###
GET {{api}}/employees
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/employees/assets
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/employees/76
Authorization: Bearer {{loginReq.response.body.$.token}}
###
PUT {{api}}/employees/75
Authorization: Bearer {{loginReq.response.body.$.token}}
Content-Type: application/json

{
  "name":"test266@gmail.com",
  "status":"inactive",
  "logo":"ffgfg",
  "email3":"test23@gmail.com",
  "branch": { "id":3, "name": "c" },
  "assets": [
    {
      "name": "ssadasda",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    },{
      "name": "ssfsadsdsad",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    },{
      "name": "ssfsadsssdsad",
      "description": "ss",
      "givenDate": "2022-01-01",
      "returnDate": "2024-01-01"
    }
  ]
}


###
GET {{api}}/attendances?from=2024-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/attendances/companywise?date=2024-02-16
Authorization: Bearer {{loginReq.response.body.$.token}}
###
GET {{api}}/attendances/75?from=2024-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/attendances/companywise?date=2024-11-10
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/attendances
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

[
  { "arrivalTime": "09:12:12", "leaveTime": "11:12:12", "date": "2024-02-15", "employee": {"id": 75} },
  { "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-16", "employee": {"id": 75} },
  { "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-17", "employee": {"id": 75, "names": "ho"} }
]
###
PUT {{api}}/attendances/12
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "arrivalTime": "10:12:12", "leaveTime": "11:12:12", "date": "2024-02-16", "employee": {"id": 75} }

###
DELETe {{api}}/attendances/12
Authorization: Bearer {{loginReq.response.body.$.token}}



###
GET {{api}}/leaves?from=2011-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/leaves/75?from=2024-02-16&to=2024-02-17
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/leaves?from=2023-12-15&to=2024-12-14
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{
  "from": "2024-02-16",
  "to": "2024-02-17",
  "reason": "Chill",
  "type": "paid",
  "status": "pending",
  "duration": "fullday",
  "shift": "firstHalfDay",
  "employee": {"id": 75}
}
###
PUT {{api}}/leaves/12
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "shift": "secondHalfDay" }

###
delete {{api}}/leaves/1
Authorization: Bearer {{loginReq.response.body.$.token}}



###
GET {{api}}/salaries?from=2011-01-01&to=2048-01-01
Authorization: Bearer {{loginReq.response.body.$.token}}

###
GET {{api}}/salaries/75?from=2024-02-16&to=2024-02-17
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/salaries?from=2023-12-15&to=2024-12-14
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{
  "month": "2024-01-01",
  "paidAt": "2024-01-14",
  "overtime": 6,
  "overtimePayment": 345,
  "lateMinutes": 5,
  "latePenalty": 14,
  "bonus": 4,
  "totalSalary": 3456,
  "paymentMethod": "bKash",
  "status": "paid",
  "employee": {"id": 75}
}
###
PUT {{api}}/salaries/1
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "status": "paid" }

###
DELETe {{api}}/salaries/1
Authorization: Bearer {{loginReq.response.body.$.token}}




###
GET {{api}}/monthly-salaries/companies?monthStartDate=2024-02-15
Authorization: Bearer {{loginReq.response.body.$.token}}

###
POST {{api}}/monthly-salaries
Content-Type: application/json
Authorization: Bearer {{loginReq.response.body.$.token}}

{ "startDate": "2024-02-15", "endDate": "2024-03-14" }


###
POST {{host}}/test
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="json"

{"hi":"bye"}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< "./env.sample"
------WebKitFormBoundary7MA4YWxkTrZu0gW--

# ALTER TABLE `employee_leave` CHANGE `duration` `duration` ENUM('fullday','first_halfday','second_halfday') NOT NULL DEFAULT 'fullday';
# ALTER TABLE `monthly_salary` ADD `leaveEncashment` DECIMAL(9,2) NOT NULL AFTER `bonus`;
# ALTER TABLE `employee_salary` ADD `remarks` VARCHAR(100) NULL AFTER `wordLimit`;
# UPDATE `employee_attendance` SET `late` = `late` - 10 WHERE `late` > 10;
# UPDATE `employee_attendance` SET `overtime` = `overtime` - 10 WHERE `overtime` > 10;

# update imran to 999
UPDATE `employee` SET `id` = '61' WHERE `employee`.`id` = 84;
# update nafis to 998
UPDATE `employee` SET `id` = '62' WHERE `employee`.`id` = 87;
# update new user to 84
UPDATE `employee` SET `id` = '84' WHERE `employee`.`id` = 88;

ALTER TABLE `employee` AUTO_INCREMENT = 1;

INSERT INTO `employee` (`id`, `name`, `phoneNumber`, `altPhoneNumber`, `email`, `dateOfBirth`, `fullAddress`, `gender`, `photo`, `dateOfJoining`, `basicSalary`, `houseRent`, `foodCost`, `conveyance`, `medicalCost`, `totalSalary`, `loanTaken`, `loanRemaining`, `taskWisePayment`, `wordLimit`, `officeStartTime`, `officeEndTime`, `checkedInLateFee`, `overtime`, `noticePeriod`, `noticePeriodRemark`, `extraBonus`, `status`, `createdDate`, `companyId`, `departmentId`, `branchId`, `designationId`, `dutyTypeId`, `salaryTypeId`) VALUES (NULL, 'fdgf@gdf.com', 'fdgf@gdf.com', 'fdgf@gdf.com', 'fdgf@gdf.com', '2025-03-05', 'fdgf@gdf.com', 'Male', 'fdgf@gdf.com', '2025-03-12', '12', '12', '12', '12', '12', '12', '1', '1', NULL, NULL, '17:37:31', '49:37:31', 'applicable', 'applicable', NULL, NULL, '', 'active', 'current_timestamp(6).000000', '3', '7', '1', '18', '1', '1');

ALTER TABLE `monthly_salary` CHANGE `leave` `leave` DECIMAL(9,2) NOT NULL;
ALTER TABLE `monthly_salary` CHANGE `leaveDeduction` `leaveDeduction` DECIMAL(9,2) NOT NULL;
ALTER TABLE `monthly_salary` ADD `unitOvertimePayment` decimal(9,2) NOT NULL AFTER `overtime`;
ALTER TABLE `monthly_salary` ADD `absence` decimal(3,1) NOT NULL AFTER `leave`;
ALTER TABLE `monthly_salary` ADD `unitAbsenceDeduction` decimal(9,2) NOT NULL AFTER `absence`;
ALTER TABLE `monthly_salary` ADD `absenceDeduction` decimal(9,2) NOT NULL AFTER `leaveDeduction`;
ALTER TABLE `monthly_salary` ADD `unitLateDeduction` decimal(9,2) NOT NULL AFTER `late`;
# UPDATE `monthly_salary` SET `unitOvertimePayment` = CASE WHEN `overtime` = 0 THEN `basicSalary` / 208 * 3 / 60 ELSE `overtimePayment` / `overtime` END;
UPDATE `monthly_salary` SET `unitOvertimePayment` = ((`basicSalary` / 208) * 3) / 60;
UPDATE `monthly_salary` SET `unitLateDeduction` = 10;
UPDATE `monthly_salary` SET `unitAbsenceDeduction` = CASE WHEN `leave` = 0 THEN 0 ELSE `leaveDeduction` / `leave` END;
UPDATE `employee` SET `loanRemaining` = `loanTaken`;
UPDATE `monthly_salary` SET `loanDeduction` = 0;
# TODO: delete loan installment
# TODO: delete loanTaken

ALTER TABLE `employee` MODIFY `taskWisePayment` DECIMAL(9,2) NULL;
SELECT `id`,`name`,`overtime`,`taskWisePayment` from `employee` where `id` in (15,16,17,18,19,20,21,22,23,24,25,27,34,35,38,39,40,43,45,46,49,52,54,55,57,58,65,67,77,78,79,86,87,88);
UPDATE `employee` SET `overtime`='applicable',`taskWisePayment`=0.6 where `id` in (15,16,17,18,19,20,21,22,23,24,25,27,34,35,38,39,40,43,45,46,49,52,54,55,57,58,65,67,77,78,79,86,87,88);
